New Files/Project/main/get_data/urls.py
from django.urls import path
from . import views

app_name = 'get_data'

urlpatterns = [
    path('', views.getdata, name='getdata'),
]

New Files/Project/main/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('get-data/', include('get_data.urls', namespace='get_data')),
    path('save-data/', include('save_data.urls')),
    path('scraper/', include('scraper.urls')),
    path('sign-up/', include('sign_up.urls')),
    path('login/', include('login.urls')),
    path('post/', include('post.urls')),
]

New Files/Project/main/get_data/models.py
from django.db import models

# Create your models here.

New Files/Project/main/get_data/old.data/views.py
import firebase_admin
from firebase_admin import db, credentials, storage
from django.shortcuts import render
import base64, os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#Path to the Firebase admin SDK JSON file
FIREBASE_ADMIN_SDK_FILE = os.path.join(BASE_DIR, 'main', 'firebase_config.json')

#Initialize the Firebase app with the admin SDK credentials
cred = credentials.Certificate(FIREBASE_ADMIN_SDK_FILE)
firebase_admin.initialize_app(cred, {
'databaseURL': 'https://authentication-2244f-default-rtdb.firebaseio.com',
'storageBucket': 'authentication-2244f.appspot.com'
})

def index(request):
    # Get data from Firebase Realtime Database
    ref = db.reference('Ads').order_by_key()
    data_dict = dict(reversed(list(ref.get().items())))
    ads_names = list(data_dict.values())

    app = firebase_admin.get_app()
    bucket = storage.bucket(app=app)

    images = []
    for blob in bucket.list_blobs():
        if blob.content_type.startswith('image/'):
            image_data = blob.download_as_bytes()
            encoded_data = base64.b64encode(image_data).decode('utf-8')
            images.append('data:{};base64,{}'.format(blob.content_type, encoded_data))

    context = {
        'ads_names': ads_names,
        'images': images,
    }
    return render(request, 'get_data.html', context)

New Files/Project/main/get_data/views.py
import firebase_admin
from firebase_admin import db, credentials, storage
from django.shortcuts import render
import base64, os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#Path to the Firebase admin SDK JSON file
FIREBASE_ADMIN_SDK_FILE = os.path.join(BASE_DIR, 'main', 'firebase_config.json')

#Initialize the Firebase app with the admin SDK credentials
cred = credentials.Certificate(FIREBASE_ADMIN_SDK_FILE)
firebase_admin.initialize_app(cred, {
'databaseURL': 'https://authentication-2244f-default-rtdb.firebaseio.com',
'storageBucket': 'authentication-2244f.appspot.com'
})

def getdata(request):
    search_query = request.GET.get('search')
    
    ref = db.reference('Details').order_by_key()
    data_dict = dict(ref.get() or {})

    ads = []
    for unique_code, ad_data in data_dict.items():
        ad = {}
        ad_name = list(ad_data.keys())[0]
        ad['name'] = ad_name
        ad['location'] = ad_data[ad_name]['location']
        ad['phone_number'] = ad_data[ad_name]['phone_number']
        ad['cost'] = ad_data[ad_name]['cost']
        ads.append(ad)

    if search_query:
        ads = [ad for ad in ads if search_query.lower() in ad['name'].lower()]

    app = firebase_admin.get_app()
    bucket = storage.bucket(app=app)

    images = []
    for ad in ads:
        blob = bucket.blob(ad['name'])
        if blob.exists():
            image_data = blob.download_as_bytes()
            encoded_data = base64.b64encode(image_data).decode('utf-8')
            images.append('data:{};base64,{}'.format(blob.content_type, encoded_data))

    context = {
        'ads': ads,
        'images': images,
        'search_query': search_query,
    }
    return render(request, 'get_data.html', context)

New Files/Project/main/get_data/templates/get_data.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/get_data_styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>    
    <h1 class="header">Home
    <br>
    <a style="color: yellow; font-size: 20px;" href="{% url 'post' %}">Post Ad Now!</a>
    </h1>  
    
    <form class="form" method="GET" action="{% url 'get_data:getdata' %}">
        <input class="form" type="text" name="search" id="search" placeholder="Search">
        <button class="form" type="button" onclick="startDictation('search')"><i class="fa fa-microphone"></i></button>
        <button class="form" type="submit">Search</button>
    </form>
    <div class="grid" style="margin-top: 10px;">
        {% if ads %}
            {% for images in images %}
            <div class="box row column">
                <div class="image-box">
                    <img class="image" id="image{{ forloop.counter }}" src="{{ image }}" alt="Ad Image">
                </div>
                {% for ad in ads %}
                    {% if forloop.counter == forloop.parentloop.counter %}
                    <b><p>{{ ad.name }}</p></b>
                    <p>{{ ad.location }}</p>
                    <p>{{ ad.phone_number }}</p>
                    <p>{{ ad.cost }}</p>
                    {% endif %}
                {% endfor %}
            </div>
            {% endfor %}
        {% else %}
            <p class="no-data">No data found.</p>
        {% endif %}
    </div>

    {% block scripts %}
    <script>
        {% for image in images %}
            document.getElementById("image{{ forloop.counter }}").src = "{{ image }}";
        {% endfor %}
    </script>
    {% endblock %}
    <script src="{% static 'js/get_data_script.js' %}"></script>
</body>
</html>